// Codegen: contract/openapi.json → typed client types + operation manifest +
// docs/tools.md. Deterministic (sorted, no timestamps) so `check:generated`
// can assert no drift. Spec §3.6.
//
// `buildOutputs()` returns { relativePath: content } and is reused by
// scripts/check-generated.ts; running this file directly writes them to disk.

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

import openapiTS, { astToString } from 'openapi-typescript';

import { DEFERRED_TOOLS, TOOL_CATALOG } from '../packages/tools/src/catalog.ts';

const ROOT = resolve(import.meta.dirname, '..');
const CONTRACT = resolve(ROOT, 'contract/openapi.json');
const HEADER = '// AUTO-GENERATED by scripts/generate.ts — do not edit. Run `pnpm generate`.\n';
const METHODS = ['get', 'post', 'put', 'patch', 'delete'] as const;

interface OpenApiDoc {
  info: { title: string; version: string };
  security?: Array<Record<string, string[]>>;
  paths: Record<string, Record<string, OpenApiOp>>;
  components: { schemas: Record<string, unknown> };
}
interface OpenApiOp {
  operationId?: string;
  summary?: string;
  security?: Array<Record<string, string[]>>;
}

function loadContract(): OpenApiDoc {
  return JSON.parse(readFileSync(CONTRACT, 'utf8')) as OpenApiDoc;
}

async function genTypes(doc: OpenApiDoc): Promise<string> {
  const ast = await openapiTS(doc as unknown as Parameters<typeof openapiTS>[0]);
  return `${HEADER}\n${astToString(ast)}`;
}

function securityOf(op: OpenApiOp, doc: OpenApiDoc): 'apiKey' | 'bearer' {
  const names = (op.security ?? doc.security ?? []).flatMap((s) => Object.keys(s));
  if (names.includes('apiKeyAuth')) return 'apiKey';
  return 'bearer';
}

interface OpEntry {
  operationId: string;
  method: string;
  path: string;
  summary: string;
  security: 'apiKey' | 'bearer';
}

function collectOps(doc: OpenApiDoc): OpEntry[] {
  const entries: OpEntry[] = [];
  for (const [path, item] of Object.entries(doc.paths)) {
    for (const method of METHODS) {
      const op = item[method];
      if (!op?.operationId) continue;
      entries.push({
        operationId: op.operationId,
        method: method.toUpperCase(),
        path,
        summary: op.summary ?? '',
        security: securityOf(op, doc),
      });
    }
  }
  return entries.sort((a, b) => a.operationId.localeCompare(b.operationId));
}

function genOperations(doc: OpenApiDoc): string {
  const rows = collectOps(doc)
    .map(
      (e) =>
        `  ${JSON.stringify(e.operationId)}: { operationId: ${JSON.stringify(e.operationId)}, ` +
        `method: ${JSON.stringify(e.method)}, path: ${JSON.stringify(e.path)}, ` +
        `summary: ${JSON.stringify(e.summary)}, security: ${JSON.stringify(e.security)} },`,
    )
    .join('\n');
  return `${HEADER}
export interface OperationMeta {
  operationId: string;
  method: 'GET' | 'POST' | 'PUT' | 'PATCH' | 'DELETE';
  path: string;
  summary: string;
  security: 'apiKey' | 'bearer';
}

export const OPERATIONS = {
${rows}
} as const satisfies Record<string, OperationMeta>;

export type OperationId = keyof typeof OPERATIONS;
`;
}

function costLabel(cost: 0 | 1 | '1/0'): string {
  if (cost === 0) return 'free';
  if (cost === 1) return '1 credit';
  return '1 credit (create) / 0 (update)';
}

function genToolsDoc(doc: OpenApiDoc): string {
  const groups: Array<'Convert' | 'Read' | 'Write' | 'Share'> = [
    'Convert',
    'Read',
    'Write',
    'Share',
  ];
  const sections = groups
    .map((group) => {
      const rows = TOOL_CATALOG.filter((t) => t.group === group)
        .map((t) => {
          const ops = Array.isArray(t.operationId) ? t.operationId.join(' + ') : t.operationId;
          return `| \`${t.name}\` | ${costLabel(t.cost)} | ${t.description} <br/>_(${ops})_ |`;
        })
        .join('\n');
      return `### ${group}\n\n| Tool | Cost | What it does |\n| --- | --- | --- |\n${rows}\n`;
    })
    .join('\n');

  const deferred = DEFERRED_TOOLS.map((t) => `- \`${t.name}\` (\`${t.operationId}\`)`).join('\n');

  return `${HEADER}
# mdtidy MCP tools

> Generated from \`contract/openapi.json\` (${doc.info.title} ${doc.info.version}). Run \`pnpm generate\`.

Authenticate with an mdtidy API key (\`mt_live_…\` for production, \`mt_test_…\` for
sandbox). Create one at <https://mdtidy.com/account/api-keys>. Credit costs are
shown per tool; failed renders are refunded automatically.

## Shipped tools

${sections}
## Deferred tools

Generated and tested, but intentionally not exposed in v1 (spec §3.4). Each is a
single registry entry to enable when a real need appears:

${deferred}
`;
}

export async function buildOutputs(): Promise<Record<string, string>> {
  const doc = loadContract();
  return {
    'packages/client/src/generated/types.ts': await genTypes(doc),
    'packages/client/src/generated/operations.ts': genOperations(doc),
    'docs/tools.md': genToolsDoc(doc),
  };
}

async function main(): Promise<void> {
  const outputs = await buildOutputs();
  for (const [rel, content] of Object.entries(outputs)) {
    const abs = resolve(ROOT, rel);
    mkdirSync(dirname(abs), { recursive: true });
    writeFileSync(abs, content);
    console.log('wrote', rel);
  }
}

const isMain = process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href;
if (isMain) await main();
